//
//  BuckwalterTable.swift
//  WholeQuran
//
//  Created by  Sergey Dolin on 12.07.2021.
//

class BuckwalterTable: EncodingTableBase {
    public static let buckwalterTable: BuckwalterTable = BuckwalterTable()

    private override init() {
        super.init()
        self.addItem(UnicodeType.Hamza, "\'", CharacterType.Hamza)
        self.addItem(UnicodeType.AlifWithHamzaAbove, ">", CharacterType.Alif, DiacriticType.HamzaAbove)
        self.addItem(UnicodeType.WawWithHamzaAbove, "&", CharacterType.Waw, DiacriticType.HamzaAbove)
        self.addItem(UnicodeType.AlifWithHamzaBelow, "<", CharacterType.Alif, DiacriticType.HamzaBelow)
        self.addItem(UnicodeType.YaWithHamzaAbove, "}", CharacterType.Ya, DiacriticType.HamzaAbove)
        self.addItem(UnicodeType.Alif, "A", CharacterType.Alif)
        self.addItem(UnicodeType.Ba, "b", CharacterType.Ba)
        self.addItem(UnicodeType.TaMarbuta, "p", CharacterType.TaMarbuta)
        self.addItem(UnicodeType.Ta, "t", CharacterType.Ta)
        self.addItem(UnicodeType.Tha, "v", CharacterType.Tha)
        self.addItem(UnicodeType.Jeem, "j", CharacterType.Jeem)
        self.addItem(UnicodeType.HHa, "H", CharacterType.HHa)
        self.addItem(UnicodeType.Kha, "x", CharacterType.Kha)
        self.addItem(UnicodeType.Dal, "d", CharacterType.Dal)
        self.addItem(UnicodeType.Thal, "*", CharacterType.Thal)
        self.addItem(UnicodeType.Ra, "r", CharacterType.Ra)
        self.addItem(UnicodeType.Zain, "z", CharacterType.Zain)
        self.addItem(UnicodeType.Seen, "s", CharacterType.Seen)
        self.addItem(UnicodeType.Sheen, "$", CharacterType.Sheen)
        self.addItem(UnicodeType.Sad, "S", CharacterType.Sad)
        self.addItem(UnicodeType.DDad, "D", CharacterType.DDad)
        self.addItem(UnicodeType.TTa, "T", CharacterType.TTa)
        self.addItem(UnicodeType.DTha, "Z", CharacterType.DTha)
        self.addItem(UnicodeType.Ain, "E", CharacterType.Ain)
        self.addItem(UnicodeType.Ghain, "g", CharacterType.Ghain)
        self.addItem(UnicodeType.Tatweel, "_", CharacterType.Tatweel)
        self.addItem(UnicodeType.Fa, "f", CharacterType.Fa)
        self.addItem(UnicodeType.Qaf, "q", CharacterType.Qaf)
        self.addItem(UnicodeType.Kaf, "k", CharacterType.Kaf)
        self.addItem(UnicodeType.Lam, "l", CharacterType.Lam)
        self.addItem(UnicodeType.Meem, "m", CharacterType.Meem)
        self.addItem(UnicodeType.Noon, "n", CharacterType.Noon)
        self.addItem(UnicodeType.Ha, "h", CharacterType.Ha)
        self.addItem(UnicodeType.Waw, "w", CharacterType.Waw)
        self.addItem(UnicodeType.AlifMaksura, "Y", CharacterType.AlifMaksura)
        self.addItem(UnicodeType.Ya, "y", CharacterType.Ya)
        self.addItem(UnicodeType.Fathatan, "F", DiacriticType.Fathatan)
        self.addItem(UnicodeType.Dammatan, "N", DiacriticType.Dammatan)
        self.addItem(UnicodeType.Kasratan, "K", DiacriticType.Kasratan)
        self.addItem(UnicodeType.Fatha, "a", DiacriticType.Fatha)
        self.addItem(UnicodeType.Damma, "u", DiacriticType.Damma)
        self.addItem(UnicodeType.Kasra, "i", DiacriticType.Kasra)
        self.addItem(UnicodeType.Shadda, "~", DiacriticType.Shadda)
        self.addItem(UnicodeType.Sukun, "o", DiacriticType.Sukun)
        self.addItem(UnicodeType.Maddah, "^", DiacriticType.Maddah)
        self.addItem(UnicodeType.HamzaAbove, "#", DiacriticType.HamzaAbove)
        self.addItem(UnicodeType.AlifKhanjareeya, "`", CharacterType.Alif, DiacriticType.AlifKhanjareeya)
        self.addItem(UnicodeType.AlifWithHamzatWasl, "{", CharacterType.Alif, DiacriticType.HamzatWasl)
        self.addItem(UnicodeType.SmallHighSeen, ":", CharacterType.SmallHighSeen)
        self.addItem(UnicodeType.SmallHighRoundedZero, "@", CharacterType.SmallHighRoundedZero)
        self.addItem(UnicodeType.SmallHighUprightRectangularZero, "\"", CharacterType.SmallHighUprightRectangularZero)
        self.addItem(UnicodeType.SmallHighMeemIsolatedForm, "[", CharacterType.SmallHighMeemIsolatedForm)
        self.addItem(UnicodeType.SmallLowSeen, ";", CharacterType.SmallLowSeen)
        self.addItem(UnicodeType.SmallWaw, ",", CharacterType.SmallWaw)
        self.addItem(UnicodeType.SmallYa, ".", CharacterType.SmallYa)
        self.addItem(UnicodeType.SmallHighNoon, "!", CharacterType.SmallHighNoon)
        self.addItem(UnicodeType.EmptyCentreLowStop, "-", CharacterType.EmptyCentreLowStop)
        self.addItem(UnicodeType.EmptyCentreHighStop, "+", CharacterType.EmptyCentreHighStop)
        self.addItem(UnicodeType.RoundedHighStopWithFilledCentre, "%", CharacterType.RoundedHighStopWithFilledCentre)
        self.addItem(UnicodeType.SmallLowMeem, "]", CharacterType.SmallLowMeem)
    }
}
